name: CD pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    # Only run if the CI pipeline was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted


    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      # Minikube deployment
      - name: Check Minikube status
        run: |
          minikube status || minikube start

    
      # Deploy to Minikube
      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Minikube service URL
        run: |
          minikube service weather-ml-app --url

      - name: Test Application Endpoint
        run: |
          APP_URL=$(minikube service weather-ml-app --url)
          curl -f $APP_URL || exit 1


